channel_targets:
  - cctbx-nightly main
python:
  - 3.7.* *_cpython  # [x86_64]
  - 3.8.* *_cpython
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.12.* *_cpython
python_impl:
  - cpython    # [x86_64]
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython
numpy:
  - 1.20    # [x86_64]
  - 1.22
  - 1.22
  - 1.22
  - 1.23
  - 1.26
